#!/usr/bin/env python

from time import sleep
from subprocess import call

coordinates = [
  (507, 900 - 181), (476, 900 - 203), (436, 900 - 223),
  (409, 900 - 213), (428, 900 - 193), (428, 900 - 164),
  (447, 900 - 142), (455, 900 - 175), (477, 900 - 170),
  (496, 900 - 145), (534, 900 - 131),
]

sleep(5)

for j in range(25):
  for i in range(len(coordinates)):
    x, y = coordinates[i]
    cmd = "./click -x {} -y {}".format(x, y)
    call(cmd.split())
    sleep(1.0 / 1000)
