#!/usr/bin/env python

from subprocess import call

def click(x, y):
  print "./click -x {} -y {}".format(x, y)
  # call("./click -x {} -y {}".format(x, y))

coordinates = [
  (534, 131),
  (496, 145),
  (477, 170),
  (455, 175),
  (447, 142),
  (428, 164),
  (428, 193),
  (409, 213),
  (436, 223),
  (476, 203),
  (507, 181)
]

for x, y in coordinates:
  click(x, y)
